use std::process::Command;

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = std::path::Path::new(&out_dir);

    // Pre-assemble pvm.s (COR24 assembly → machine code) at build time.
    let pvm_source = std::fs::read_to_string("asm/pvm.s").expect("asm/pvm.s");
    let mut asm = cor24_emulator::Assembler::new();
    let result = asm.assemble(&pvm_source);
    if !result.errors.is_empty() {
        for e in &result.errors {
            eprintln!("pvm.s: {e}");
        }
        panic!("pvm.s assembly failed");
    }
    std::fs::write(out_path.join("pvm.bin"), &result.bytes).unwrap();

    let labels = [
        (
            "vm_state",
            result.labels.get("vm_state").copied().unwrap_or(0),
        ),
        (
            "eval_stack",
            result.labels.get("eval_stack").copied().unwrap_or(0),
        ),
        (
            "call_stack",
            result.labels.get("call_stack").copied().unwrap_or(0),
        ),
        (
            "code_seg",
            result
                .labels
                .get("code_buf")
                .or(result.labels.get("code_seg"))
                .copied()
                .unwrap_or(0),
        ),
        (
            "vm_loop",
            result.labels.get("vm_loop").copied().unwrap_or(0),
        ),
        (
            "code_ptr",
            result.labels.get("code_ptr").copied().unwrap_or(0),
        ),
    ];
    let mut labels_rs = String::from("// Generated by build.rs — do not edit\n");
    labels_rs.push_str("pub const PVM_LABELS: &[(&str, u32)] = &[\n");
    for (name, addr) in &labels {
        labels_rs.push_str(&format!("    (\"{name}\", 0x{addr:06X}),\n"));
    }
    labels_rs.push_str("];\n");
    std::fs::write(out_path.join("pvm_labels.rs"), labels_rs).unwrap();
    println!("cargo:rerun-if-changed=asm/pvm.s");

    // Copy basic.p24 into the build output so it can be embedded.
    let basic_p24 = std::fs::read("assets/basic.p24").expect("assets/basic.p24");
    std::fs::write(out_path.join("basic.p24"), &basic_p24).unwrap();
    println!("cargo:rerun-if-changed=assets/basic.p24");

    // Short git SHA
    let sha = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    // Build host
    let host = Command::new("hostname")
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    // ISO timestamp
    let timestamp = Command::new("date")
        .args(["-u", "+%Y-%m-%dT%H:%M:%SZ"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    println!("cargo:rustc-env=BUILD_SHA={sha}");
    println!("cargo:rustc-env=BUILD_HOST={host}");
    println!("cargo:rustc-env=BUILD_TIMESTAMP={timestamp}");
}
